version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

upx:
  - enabled: true
    compress: best
    lzma: true
    # TODO: delete this string when upx fix segfault
    # https://github.com/upx/upx/issues/612
    goos: [linux, windows]

builds:
  - id: "bounceback"
    main: ./cmd/bounceback
    binary: bounceback
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: "bounceback"
    ids:
      - "bounceback"
    formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - data/
      - scripts/
      - LICENSE
      - README.md
      - config.yml

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
